### ISSUE TITLE
Create API for filter configuration

### ISSUE THREAD

**Issue by petebrowne** [localmed/django-assetfiles#5]
[Some Proposed Designs](https://gist.github.com/petebrowne/4750305)

There needs to be a way of combining filters, targeting specific files, and also concatenation. Right now this is not possible with the current filter and configuration designs. File matching and reversing should be separated from filters altogether as well.

**Comment by petebrowne** [comment]
I'm currently leaning towards [option 2](https://gist.github.com/petebrowne/4750305#file-filters_2-py). Full glob syntax (notably recursion) is not supported in python though, which means we'll probably have to depend on [glob2](https://github.com/miracle2k/python-glob2) (which does not support python 3.x). Why, python why??

**Comment by jeremyswitzer** [comment]
Have you considered something like [finders](https://docs.djangoproject.com/en/1.3/ref/contrib/staticfiles/#std:setting-STATICFILES_FINDERS) config setting? It would be like [option 3](https://gist.github.com/petebrowne/4750305#file-filters_3-py), but all the matching and reversing could be done in a class that could simply be extended if it needed matching customization or multiple filter inclusion.

I can definitely see the benefit of being able to customize the filters all in the settings or a single project file, but this way, a developer who might need that specific level of pattern matching could override the default (using glob2 if their project was only 2.x) and including the new class in the config in place of the standard one.
